### ISSUE TITLE
Aplicar el formato requerido en la generación de los gráficos en Excel

### ISSUE THREAD

**Issue by larvamdp** [gino08/excelMacro#32]
Aplicar el formato requerido en la generación de los gráficos en Excel
Este formato es el que se debe utilizar al volcar los gráficos en el PPT

**Comment by gino08** [comment]
[Template Argentina-2017-final.pptx](https://github.com/gino08/excelMacro/files/1134100/Template.Argentina-2017-final.pptx)
Se adjunta el template con los formatos requeridos.

**Comment by larvamdp** [comment]
Se van a especializar issues particulares. Se cierra este
