### ISSUE TITLE
Al generar una demografía unificada no se genera correctamente el gráfico

### ISSUE THREAD

**Issue by larvamdp** [gino08/excelMacro#39]
Al generar una demografía unificada no se genera correctamente el gráfico.
Probando con el archivo de Demografías de Oracle, si genero una demografía unificada desde AM1 hasta BI1 genera un gráfico vacío.

**Comment by gino08** [comment]
Los datos a completar para que se generen la Demografía Unificada son las columnas "Hoja de Datos", "Dimensión Inicial", "Dimensión Final", "Valor Inicial" y "Valor Final". 
También es recomendable que en el "Tipo de Gráfico" se seleccione el tipo "Barras" ya que generalmente los gráficos unificados contienen muchas dimensiones y es más fácil la lectura y comprensión en un gráfico de Barras que en uno de Torta. 

Los datos para que funcione correctamente el ejemplo de Oracle serían:
Hoja de Datos: **Demografia**
Dimensión Inicial: **AM2**
Dimensión Final: **BI2**
Valor Inicial: **AM17**
Valor Final: **BI17**
