### ISSUE TITLE
Corregir al presionar el botón Cancelar en la generación del PPT

### ISSUE THREAD

**Issue by gino08** [gino08/excelMacro#42]
Se debe corregir cuando se presiona el botón cancelar en la generación del PPT en los siguientes casos:

1. Al cancelar en la selección del Template
2. Al cancelar en la selección de la Carpeta de Destino
3. Al cancelar al indicar el nombre del Archivo de Destino

**Comment by larvamdp** [comment]
Si se da Cancelar al momento de elegir el nombre del archivo da error
